### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by kevcube** [modulestf/public#2]
## Is your request related to a problem? Please describe.
Unable to test whether this plugin meets my needs on M1 Mac. I'm looking for better terragrunt syntax highlighting.

## Describe the solution you'd like.
Current plugins supporting terragrunt HCL files only look for exactly `terragrunt.hcl`. That filename is no longer a prescriptive standard in terragrunt, so for example I have a `root.hcl` file which gets no highlighting treatment.

## Describe alternatives you've considered.
I was gonna compile it myself then found it's not open-source 😅

**Comment by antonbabenko** [comment]
We are still in the development phase and M1 Mac is not our top priority right now. It will be resolved when we add more features (incl. semantic highlighting for terragrunt files).

I keep this issue open for the time being.

**Comment by kevcube** [comment]
looks like this is included now. closing
